---
- hosts: all
  gather_facts: no

  tasks :
    - name: update eduadmin
      win_user:
        name: eduadmin
#        password: tnpqhfp^^10
        password: "{{ var_pass }}"
        state: present
