- hosts: all

  tasks :
    - name         : Get User List
      shell        : "yum clean all"
      changed_when : False
      register     : update
      when: ansible_distribution == 'CentOS' 

    - name         : Get User List
      shell        : "yum -y update {{ pkg }}"
      changed_when : False
      register     : update
      when: ansible_distribution == 'CentOS' 

    - name  : debug update
      debug : var=update.stdout_lines
      when: ansible_distribution == 'CentOS'  
