---
- hosts: all
  gather_facts: no

  tasks :
    - name: Register loop output as a variable
      ansible.builtin.shell: "chage -E '2023-12-31' {{ item }}"
      loop:
        - "jhjo1"
        - "jwkum"
        - "khlee2"
        - "kyseo"
        - "sghan1"
        - "choh"
        - "kwlee1"
        - "ybkim1"
        - "kwhan"
        - "khham"
        - "shkim9"
      register: chage

   
