- hosts: all
  become: yes
  task:
  - name: Make sure group wheel is not in the sudoers configuration
    ansible.builtin.lineinfile:
      path: /etc/sudoers
      state: absent
      regexp: '^%wheel'