---
- hosts: all
  
  tasks:
    - name: PSWindowUpdate module file copy
      win_get_url:
       url: "{{ url_path }}"
       dest: "{{ dest_path }}"
       url_username: "{{ url_user }}"
       url_password: "{{ url_passwd }}"
     
    - name: Set ExecutionPolicy
      win_shell: Set-ExecutionPolicy RemoteSigned
     
    - name: Module Import
      win_shell: Import-Module PSWindowsUpdate
    
    - name: Get Module
      win_shell: Get-Command -module PSWindowsUpdate
      register: result
    
    - debug: var=result
