---
- hosts: all
  
  tasks:
    - name: Check Process Running
      win_shell: Get-Process {{ process_name }}
      register: result
      
    - name: Print Result
      debug:
        var: result.stdout_lines
