---
- hosts: all
  
  tasks:
    - name: 1. copy uptime.exe file
      win_copy:
      src: "{{ copy_src }}"
      dest: "{{ copy_dest }}"
    
    - name: 2. execute uptime.exe
      win_command: 'C:\uptime.exe'
      register: result
      ignore_errors: True

    - debug: msg="{{ result.stdout }}"
    
    
