---
- hosts: all
  remote_user: mheo
  tasks:
  - name: New System User
    user: name="{{ add_user_name }}"
        password='$6$VVNDovQg$htL4uljQmvNXTYRgLm5cxHwKBF8asgxZNGZPyCSAn.YulRibsSV5U1TthbQvTD2x2msIusBuaD20ys4gFs9u.1'
        shell=/bin/bash
    become: yes
    become_user: root
  - name: Add user to sudoers
    lineinfile: dest=/etc/sudoers
        regexp="{{ add_user_name }}   ALL"
        line="{{ add_user_name }}   ALL=(ALL)"
        state=present
    become: yes
    become_user: root