---
- hosts: all

  tasks:
    - name: Execute PS Fisst SendMassMail
      command: java -jar {{ arg }} {{ jar_name }}
      register: result_target

    - name  : debug result_target
      debug : var=result_target.stdout_lines