- hosts: all

  tasks:
    - name: Gitlab Backup Start
      command: gitlab-rake gitlab:backup:create
    
    - name: Delete old backup file
      command: find /var/opt/gitlab/backups -name "*.tar" -mtime +3 -exec rm -rf {} \;
