---
- hosts: all
  connection: local
  
  tasks:
    - name: test export grafana dashboard
      grafana_dashboard:
        grafana_url: http://grafana.eduwill.net:3000
        grafana_api_key: "{{ grafana_api_key }}"
        state: export
        org_id: 1
        uid: 9TNABBrmz
        path: "/testexport.json"
