---
- hosts: all
  gather_facts: no

  tasks:
    - name: rsyslog replace1
      lineinfile: dest=/etc/rsyslog.conf
            regexp="^kern"
            line="kern.* @172.16.10.130:5514;RSYSLOG_SyslogProtocol23Format"
            state=present

    - name: rsyslog replace2
      lineinfile: dest=/etc/rsyslog.conf
            regexp="info @172.16.30.156"
            line="*.info @172.16.10.130:5514;RSYSLOG_SyslogProtocol23Format"
            state=present

    - name: rsyslog replace3
      lineinfile: dest=/etc/rsyslog.conf
            regexp="^authpriv.* @172.16.30.156"
            line="authpriv.* @172.16.10.130:5514;RSYSLOG_SyslogProtocol23Format"
            state=present

    - name: restart service rsyslog
      service: 
        name: rsyslog
        state: restarted
