---
- hosts: all

  tasks:
    - name: Network Driver Mount
      win_mapped_drive: 
        letter: S
        path: "{{ nas_path }}"
        username: "{{ nas_username }}"
        password: "{{ nas_password }}"
