- name: Create user 
  hosts: all
  become: yes  # 관리자 권한 필요할 수 있습니다. sudo 또는 root 권한으로 실행됩니다.
  tasks:
    - name: Create group with the same name
      ansible.builtin.group:
        name: {{ group }}
        state: present

    - name: Create user jhjeon2 with password 1234
      ansible.builtin.user:
        name: {{ user }}
        group: jhjeon2  # 위에서 생성한 그룹에 추가합니다.
        password: "{{ '{{ pwd }}' | password_hash('sha512') }}"  # 비밀번호를 해싱하여 설정합니다.
        shell: /bin/bash  # 사용자의 기본 셸을 지정할 수 있습니다.
        createhome: yes  # 사용자 홈 디렉토리 생성 여부

    - name: Print created user's details
      ansible.builtin.debug:
        var: ansible_user