---
- hosts: all
  remote_user: mheo
  tasks:
    - name: '"cat /etc/shadow | grep 99999 | grep -v ":\!" | grep -v ":\*""'
      shell: 'cat /etc/shadow | grep 99999 | grep -v ":\!" | grep -v ":\*"'
      register: result
      ignore_errors: True
      become: yes
      become_user: root
    - debug: var=result
