---
- hosts: all

  tasks:
  - name: Copy telegraf agent rpm
    copy:
      src: /var/lib/awx/projects/{{ file_name }}
      dest: "{{ dest_pass }}"
      owner: root
      group: root
      mode: 0644

  - name: Install telegraf agent from yum
    yum: 
      name: "{{ dest_pass }}/{{ file_name }}"
      state: present

  - name: Original telegraf.conf Backup
    stat: path=/etc/telegraf/telegraf.conf
    register: org_conf

  - name: Original Login Banner Backup
    command: mv /etc/telegraf/telegraf.conf /etc/telegraf/telegraf.conf.bak
    when: org_conf.stat.exists

  - name: Copy telegraf config file
    copy:
      src: /var/lib/awx/projects/{{ conf_name }}
      dest: /etc/telegraf/telegraf.conf
      owner: root
      group: root
      mode: 0644

  - name: Set agent hostname in telegraf.conf
    lineinfile: dest=/etc/telegraf/telegraf.conf
      regexp="^  hostname*"
      line="  hostname = \"{{ host_name }}\""
      state=present
      
  - name: restart telegraf agent service
    systemd:
      state: restarted
      daemon_reload: yes
      name: telegraf
      enabled: true