---
- hosts: all
  
  tasks:
    - name: Original Login Banner Check
      stat: path=/etc/issue.net
      register: org_banner

    - name: Original Login Banner Backup
      command: mv /etc/issue.net /etc/issue.net.bak
      when: org_banner.stat.exists
            
    - name: Modify Custom Banner config
      lineinfile: dest=/etc/ssh/sshd_config
            regexp="Banner[\s\x20]*(none|/etc/issue.net)"
            line="Banner /etc/issue.net"
            state=present

    - name: Custom Login Banner
      copy: 
        dest: /etc/issue.net
        content: |
            ###############################################################
            # Authorized access only!                                     #
            # Disconnect IMMEDIATELY if you are not an authorized user!!! #
            # All actions Will be monitored and recorded                  #
            ############################################################### 

    - name: restart service sshd
      service: 
        name: sshd
        state: restarted
