---
- hosts: all
  
  tasks:
    - name: (U-01) Disable root remote access - commenting pts
      replace: dest=/etc/securetty
            regexp="^pts"
            replace="#pts"
      
    - name: (U-01) PermitRootLogin no
      lineinfile: dest=/etc/ssh/sshd_config
            regexp="PermitRootLogin[\s\x20]*(yes|no)"
            line="PermitRootLogin no"
            state=present
  
    - name: (U-03) modify auth required
      lineinfile: dest=/etc/pam.d/system-auth
            regexp="^auth[\s\x20]*required[\s\x20]*(pam_env.so|pam_tally2.so)"
            line="auth        required      pam_tally2.so deny=5 unlock_time=120 no_magic_root"
            state=present
      
    - name: (U-01) modify account requisite
      lineinfile: dest=/etc/pam.d/system-auth
            regexp="^account[\s\x20]*required[\s\x20]*(pam_unix.so|pam_tally2.so)"
            line="account     required      pam_tally2.so no_magic_root reset"
            state=present
      
    - name: (U-01) modify password requisite
      lineinfile: dest=/etc/pam.d/system-auth
            regexp="^password[\s\x20]*requisite"
            line="password    requisite     pam_cracklib.so try_first_pass retry=3 lcredit=1 dcredit=-1 ocredit=1"
            state=present
  
    - name: (U-01) modify password sufficient
      lineinfile: dest=/etc/pam.d/system-auth
            regexp="^password[\s\x20]*sufficient*"
            line="password    sufficient    pam_unix.so sha512 shadow nullok try_first_pass use_authtok remember=1"
            state=present

    - name: (U-02) modify auth required
      lineinfile: dest=/etc/pam.d/password-auth
            regexp="^auth[\s\x20]*required[\s\x20]*(pam_env.so|pam_tally2.so)[\s\x20]*"
            line="auth        required      pam_tally2.so deny=3 unlock_time=60"
            state=present

    - name: (U-02) modify account required
      lineinfile: dest=/etc/pam.d/password-auth
            regexp="^account[\s\x20]*required[\s\x20]*(pam_unix.so|pam_tally2.so)[\s\x20]*"
            line="account     required      pam_tally2.so"
            state=present

    - name: (U-06) modify password min length
      lineinfile: dest=/etc/login.defs
            regexp="^PASS_MIN_LEN[\s\x20]*[0-9]*"
            line="PASS_MIN_LEN    8"
            state=present

    - name: (U-07) modify password max days
      lineinfile: dest=/etc/login.defs
            regexp="^PASS_MAX_DAYS[\s\x20]*[0-9]*"
            line="PASS_MAX_DAYS  90"
            state=present

    - name: (U-08) modify password min days
      lineinfile: dest=/etc/login.defs
            regexp="^PASS_MIN_DAYS[\s\x20]*[0-9]*"
            line="PASS_MIN_DAYS  1"
            state=present

    - name: (U-11) set time out 900s
      lineinfile: dest=/etc/profile
            regexp="^(export|EXPORT)[\s\x20]*TMOUT=[0-9]*"
            line="export TMOUT=900"
            state=present

    - name: (U-13) chagne passwd file owner
      file: path=/etc/passwd
            owner=root
            group=root
            mode=0644

    - name: (U-14) chagne shoadow file owner
      file: path=/etc/shadow
            owner=root
            group=root
            mode=0400

    - name: (U-17) chagne services file owner
      file: path=/etc/services
            owner=root
            group=root
            mode=0644

    - name: (U-25) change cron.deny file owner
      file: path=/etc/cron.deny
            owner=root
            group=root
            mode=0600