---
- hosts: all
  
  tasks:
    - name: Original Login Banner Check
      stat: path=/etc/issue.net
      register: org_banner

    - name: Original Login Banner Backup
      command: mv /etc/issue.net /etc/issue.net.bak
      when: org_banner.stat.exists
            
    - name: Modify Custom Banner config
      lineinfile: dest=/etc/ssh/sshd_config
            regexp="Banner[\s\x20]*(none|/etc/issue.net)"
            line="Banner /etc/issue.net"
            state=present

    - name: Custom Login Banner
      copy: 
        dest: /etc/motd
        content: |
            ###############################################################
            # Authorized access only!                                     #
            # Disconnect IMMEDIATELY if you are not an authorized user!!! #
            # All actions Will be monitored and recorded                  #
            ############################################################### 

    - name: install snmpd
      yum: 
        name: net-snmp
        state: latest

    - name: backup config for snmpd
      command: mv /etc/snmp/snmpd.conf /etc/snmp/snmpd.conf.bak

    - name: Custom snmpd config
      copy: 
        dest: /etc/snmp/snmpd.conf
        content: |
            com2sec local 127.0.0.1 edu20!5
            com2sec mynetwork 0.0.0.0/0 edu20!5
            
            group MyRWGroup v1 local
            group MyRWGroup v2c local
            group MyRWGroup usm local
            group MyROGroup v1 mynetwork
            group MyROGroup v2c mynetwork
            group MyROGroup usm mynetwork
            
            view all included .1 80
            
            access MyROGroup "" any noauth exact all none none
            access MyRWGroup "" any noauth exact all all none
            	
            # load ave #
            load
            # disk used #
            disk /
            disk /var

    - name: restart service snmpd
      service: 
        name: snmpd
        state: restarted