- name: Create User
  hosts: all
  become: yes
   tasks:
    - name: "{{ user }} 유저 생성"
      user:
        name: "{{ user }}"
        password: "{{ pwd | password_hash('sha512') }}" # 비밀번호 설정 (암호화된 형태로 저장)
        state: present # 존재하지 않을 경우에만 유저 생성