---
- hosts: all
  tasks:
    - name: Delete Account Force
      user: name="{{ item }}"
            state=absent
            remove=yes
            force=yes
      with_items: "{{ del_user_name }}"
      register     : user_list

    - name  : debug user_list
      debug : var=user_list.stdout_lines

      
    - name: Delete normal user to sudoers
      lineinfile: dest=/etc/sudoers
            regexp="^{{ item }}"
            state=absent
      with_items: "{{ del_user_name }}"
    
    - name: Remove the user group
      group:
        name: name="{{ item }}"  # 제거할 그룹의 이름을 입력하세요.
        state: absent         # 그룹을 제거하려면 "absent"로 설정합니다.
      with_items: "{{ del_user_name }}"  
    
    - name: delete directory
      file:
        path: /home/{{item}}
        state: absent
      with_items: "{{ del_user_name }}"


