---
- name: Create user and group with specified details
  hosts: all
  become: yes
    
  tasks:
    - name: Create group with the specified name
      ansible.builtin.group:
        name: "{{ groupname }}"
        state: present

    - name: Create user with specified details
      ansible.builtin.user:
        name: "{{ username }}"
        group: "{{ groupname }}"
        password: "{{ user_password | password_hash('sha512') }}"
        shell: /bin/bash
        createhome: yes

    - name: Print created user's details
      ansible.builtin.debug:
        var: ansible_user

    - name: Allow passwordless sudo for the oneuser user
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^{{ username }}'
        line: '{{ username }} ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'

      # Optionally, if using a specific editor to modify sudoers
      environment:
        EDITOR: "/usr/bin/vim" # Replace with your preferred editor