- hosts: all
  gather_facts: no

  tasks:
    - name: Gitlab Backup Start
      shell: "/home/jenkins/entprsSales.sh;ps -ef|grep entp"
      register: final_result
      ignore_errors: True

    - name: result gogosing
      debug: var=final_result.stdout_lines
