---
- hosts: all
  
  tasks:
    - name: Execute pwdExpire.ps1
      win_command: Powershell.exe -noprofile -executionpolicy bypass -file "C:\script\pwdExpire.ps1"
      register: result
      
    - name: Print Result
      debug:
        var: result.stdout_lines
