---
- hosts: all
  
  tasks:
    - name: Install all security updates
      win_updates:
        category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
        - Updates
        reboot: "{{ reboot }}"
      register: update_rst
    
    - name: Print result
      debug:
        var: update_rst