---
- hosts: all
  
  tasks:
    - name: Check Administrators Group Member
      win_command: net localgroup Administrators
      register: result
      
    - name: Print Result
      debug:
        var: result.stdout_lines

