---
- hosts: all
  
  tasks:
    - name: Delete Old Zone File
      win_command: forfiles /p "C:\Windows\System32\dns" /m "dns_*" /c "cmd /c del @FILE"
      ignore_errors: True
      
    - name: Export bizwill.net
      win_command: dnscmd /ZoneExport bizwill.net dns_bizwill_net
      
    - name: Export eduwill.net
      win_command: dnscmd /ZoneExport eduwill.net dns_eduwill_net
      
    - name: Export hq.eduwill.net
      win_command: dnscmd /ZoneExport hq.eduwill.net dns_hq_eduwill_net
      
    - name: Export studywill.net
      win_command: dnscmd /ZoneExport studywill.net dns_studywill_net
