- hosts: all
  gather_facts: yes
  become:yes
  task:
    - name: file or dir nouser
      ansible.builtin.shell:
        cmd: find / ! \( -path '/proc/*' -prune \) -nouser >> nouser.log_`date +%Y%m%d` 
        chdir: /root/
    - name: file or dir nogroup
      ansible.builtin.shell:
        cmd: find / ! \( -path '/proc/*' -prune \) -nogroup >> nogroup.log_`date +%Y%m%d` 
        chdir: /root/