- hosts: all  # 대상 호스트 또는 그룹 이름을 입력합니다.
  #remote_user: your_remte_user  # 원격 서버에서의 사용자 이름을 입력합니다. (일반적으로 sudo 권한을 가진 사용자를 사용합니다.)
  become: yes
  tasks:
    - name: file or dir nouser
      ansible.builtin.shell:
        cmd: find / ! \( -path '/proc/*' -prune \) -nouser >> nouser.log_`date +%Y%m%d` 
        chdir: /root/
    - name: file or dir nogroup
      ansible.builtin.shell:
        cmd: find / ! \( -path '/proc/*' -prune \) -nogroup >> nogroup.log_`date +%Y%m%d` 
        chdir: /root/
    - name: file permission change
      file:
        path: "/etc/hosts"
        mode: 0600
      file:
        path: "/etc/passwd"
        mode: 0600
      file:
        path: "/etc/shadow"
        mode: 0400
      file:
        path: "/bin/su"
        mode: 4750
      file:
        path: "/etc/rsyslog.conf"
        mode: 640
      
      register: "check_log"
  
    - debug:
        msg: "{{ check_log }}"