- hosts: all  # 대상 호스트 또는 그룹 이름을 입력합니다.
  #remote_user: your_remote_user  # 원격 서버에서의 사용자 이름을 입력합니다. (일반적으로 sudo 권한을 가진 사용자를 사용합니다.)
  tasks:
    - name: Get a list of user accounts (excluding root)
      shell: "awk -F':' '($2 != \"*\" && $2 != \"!\" && $2 != \"!!\") { print $1 }' /etc/shadow"
      register: user_list

    - name: Set login threshold for all accounts (excluding root)
      shell: "pam_tally2 --user={{ item }} --reset && pam_tally2 --user={{ item }} --deny={{ login_threshold }} --unlock-time={{ unlock_time }}"
      loop: "{{ user_list.stdout_lines }}"
      vars:
        login_threshold: 5  # 설정할 로그인 임계치를 입력합니다. (로그인 실패 횟수 기준)
        unlock_time: 300  # 잠금 해제까지의 시간(초)을 입력합니다. (예: 300은 5분)

    - name: Update PAM configuration for login threshold
      lineinfile:
        dest: /etc/pam.d/common-auth
        regexp: "^auth.*required.*pam_tally2.so.*onerr=fail.*audit.*silent.*deny={{ login_threshold }}"
        line: "auth required pam_tally2.so onerr=fail audit silent deny={{ login_threshold }} unlock_time={{ unlock_time }}"
        state: present
