- name: Change PASS_MAX_DAYS in login.defs
  hosts: all
  become: true
  tasks:
    - name: Update PASS_MAX_DAYS in login.defs
      lineinfile:
        path: /etc/login.defs
        regexp: '^(\s*PASS_MAX_DAYS\s+)(\d+)'
        line: '\PASS_MAX_DAYS   90'