- hosts: all
  become: yes
  vars:
    installmode: "{{ mode }}"
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
  
    - name: Download Zabbix repository file
      get_url:
        url: "https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb"
        dest: "/tmp/"
      when: installmode == 'internal'

    - name: Install Zabbix repository package
      apt:
        deb: "/tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb"
      when: installmode == 'internal'

    
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
      when: installmode == 'internal'
    
    - name: install zabbix-agent2
      apt:
        name: zabbix-agent2
        state: present
        update_cache: true

    - name: install zabbix-agent2-plugin-postgresql
      apt:
        name: zabbix-agent2-plugin-postgresql
        state: present
        update_cache: true


    - name: install zabbix-agent2-plugin-mongodb
      apt:
        name: zabbix-agent2-plugin-mongodb
        state: present
        update_cache: true
    
    - name: Update Server line in zabbix_agent2.conf
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^Server=127.0.0.1'
        line: 'Server={{ Server }}'

    - name: Update Server line in zabbix_agent2.conf
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^ServerActive=127.0.0.1'
        line: 'ServerActive={{ Server }}:10051'

    - name: Restart zabbix-agent service
      systemd:
        name: zabbix-agent2
        enabled: yes
        state: restarted

   