- hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
  
    - name: Download Zabbix repository file
      get_url:
        url: "https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb"
        dest: "/tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb"

    - name: Install Zabbix repository package
      apt:
        deb: "/tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb"
    
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
    
    - name: install zabbix-server-mysql
      apt:
        name: zabbix-server-mysql
        state: present
        update_cache: true
    
    - name: install zabbix-frontend-php
      apt:
        name: zabbix-frontend-php
        state: present
        update_cache: true
    
    - name: install zabbix-nginx-conf
      apt:
        name: zabbix-nginx-conf
        state: present
        update_cache: true
    
    - name: install zabbix-sql-scripts
      apt:
        name: zabbix-sql-scripts
        state: present
        update_cache: true
    
    - name: install zabbix-agent
      apt:
        name: zabbix-agent
        state: present
        update_cache: true 

    - name: install mariadb-server
      apt:
        name: mariadb-server
        state: present
        update_cache: true 

    - name: Restart Chrony service
      service:
        name: mariadb
        state: restarted
    
    - name: mariadb setting
      shell: "{{ item }}"
      with_items:
        - "mysql -uroot -e \"create database zabbix character set utf8mb4 collate utf8mb4_bin;\""
        - "mysql -uroot -e \"create user zabbix@localhost identified by '{{ passwd }}';\""
        - 'mysql -uroot -e "grant all privileges on zabbix.* to zabbix@localhost;"'
        - 'mysql -uroot -e "set global log_bin_trust_function_creators = 1;"'
        - "zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -uzabbix -p{{ passwd }}"
        - 'mysql -uroot -e "set global log_bin_trust_function_creators = 0;"'
    
    



    
  