- hosts: all
  become: yes
  tasks:
    - name: Replace server_name in nginx.conf
      replace:
        path: /etc/zabbix/nginx.conf  # 파일 경로
        regexp: '^#( *server_name +)example\.com(;)?'  # 검색할 패턴
        replace: '\1   example.com;'  # 변경할 내용