apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: onepredict-net-tls
spec:
  secretName: onepredict-net-tls  # 인증서가 저장될 Secret 이름
  issuerRef:
    name: ca-issuer  # 앞서 만든 ClusterIssuer 이름
    kind: ClusterIssuer
  dnsNames:
  - onepredict.net
  - monitor.onepredict.net
  - gsc-turbo.onepredict.net
  - 