- hosts: all
  become: yes
  become_user: root
  vars:
    ansible_user: k8s
  tasks:
   - name: Update and upgrade apt packages
     apt:
       upgrade: yes
       update_cache: yes
       cache_valid_time: 86400 #One day

   - name: install curl 
     apt:
       name: curl
       state: present
       update_cache: true
  
   - name: install iftop
     apt:
       name: iftop
       state: present
       update_cache: true
   
   - name: install ntp 
     apt:
       name: chrony
       state: present
       update_cache: true
     
   - name: install ca-certificates
     apt:
       name: ca-certificates
       state: present
       update_cache: true
    
   - name: install gnupg 
     apt:
       name: gnupg
       state: present
       update_cache: true
    
   - name: install lsb
     apt:
       name: lsb-release
       state: present
       update_cache: true

   - name: install nfs-common
     apt:
       name: nfs-common
       state: present
       update_cache: true

   - name: add Docker apt-key
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

   - name: Add Docker Repository
     apt_repository:
       repo: deb https://download.docker.com/linux/ubuntu focal stable
       state: present

   - name: Update apt and install Containerd
     apt:
       name: containerd.io
       state: latest
       update_cache: true

   - name: add Kubernets apt-key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

   - name: Add Kubernetes Repository
     apt_repository:
       repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
       state: present

   - name: Update apt and install kubelet
     apt:
       name: kubelet
       state: latest
       update_cache: true

   - name: Update apt and install kubelet
     apt:
       name: kubeadm
       state: latest
       update_cache: true

   - name: Update apt and install kubelet
     apt:
       name: kubectl
       state: latest
       update_cache: true