- hosts: controller01
  become: yes
  vars:
    controller01: "10.10.40.55"
    controller02: "10.10.40.56"
    controller03: "10.10.40.57"
    worknode01: "10.10.40.80"
    worknode02: "10.10.40.81"
    worknode03: "10.10.40.82"
    vipaddr: "10.10.40.58"
    interfacename: "10.10.40"
    firstip: "10.10.40.83"
    endip: "10.10.40.85"
  tasks:
    - name: haproxy.yaml ip setup
      shell: "{{ item }}"
      with_items:
        - "sed -i s/controller_01/{{ controller01 }}/g /tmp/haproxy.yaml"
        - "sed -i s/controller_02/{{ controller02 }}/g /tmp/haproxy.yaml"
        - "sed -i s/controller_03/{{ controller03 }}/g /tmp/haproxy.yaml"
        - "sed -i 's/vipaddr/{{ vipaddr }}/g' /tmp/haproxy.yaml"
        - "sed -i 's/INTERFACENAME/{{ interfacename }}/g' /tmp/haproxy.yaml"
    - name: k8s.yaml ip setup
      shell: "{{ item }}"
      with_items:
        - "sed -i s/controller_01/{{ controller01 }}/g /tmp/k8s.yaml"
        - "sed -i s/controller_02/{{ controller02 }}/g /tmp/k8s.yaml"
        - "sed -i s/controller_03/{{ controller03 }}/g /tmp/k8s.yaml"
        - "sed -i 's/vipaddr/{{ vipaddr }}/g' /tmp/k8s.yaml"
        - "sed -i 's/INTERFACENAME/{{ interfacename }}/g' /tmp/k8s.yaml"
    - name: timezone.yaml ip setup
      shell: "{{ item }}"
      with_items:
        - "sed -i s/controller_01/{{ controller01 }}/g /tmp/k8s.yaml"
        - "sed -i s/controller_02/{{ controller02 }}/g /tmp/k8s.yaml"
        - "sed -i s/controller_03/{{ controller03 }}/g /tmp/k8s.yaml"
        - "sed -i s/worknode_01/{{ worknode01 }}/g /tmp/k8s.yaml"
        - "sed -i s/worknode_02/{{ worknode02 }}/g /tmp/k8s.yaml"
        - "sed -i s/worknode_03/{{ worknode03 }}/g /tmp/k8s.yaml"
        - "sed -i 's/vipaddr/{{ vipaddr }}/g' /tmp/k8s.yaml"
        - "sed -i 's/INTERFACENAME/{{ interfacename }}/g' /tmp/k8s.yaml"
    - name: metallb.yaml ip setup
      shell: "{{ item }}"
      with_items:
        - "sed -i s/firstIP/{{ firstip }}/g /tmp/k8s.yaml"
        - "sed -i s/endIP/{{ endtip }}/g /tmp/k8s.yaml"
       