apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-nfs-teleportpv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /NFS/teleport  # NAS 서버의 경로
    server: ceph02.bestpath.co.kr  # NFS 주소
  persistentVolumeReclaimPolicy: Retain  # PV 재사용 정책 설정 (필요에 따라 변경 가능)