- hosts: all
  become: true
  become_user: root
  tasks:
    - name: 90-installer-network.cfg 파일 수정
      lineinfile:
        path: /etc/cloud/cloud.cfg.d/90-installer-network.cfg
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^[ ]{8}- 8.8.8.8', line: '        - 10.233.0.3' }
        - { regexp: '^[ ]{8}- bestpath.co.kr', line: '        - cluster.local' }

    - name: 90-installer-network.cfg 파일 수정
      lineinfile:
        path: /etc/netplan/50-cloud-init.yaml
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^[ ]{16}- 8.8.8.8', line: '                - 10.233.0.3' }
        - { regexp: '^[ ]{16}- bestpath.co.kr', line: '                - cluster.local' }

    - name: net apply 
      command: "netplan apply"
      ignore_errors: yes



- hosts: all
  become: true
  become_user: root
  vars:
    ansible_become_pass: "@whdgus123!"
  tasks:
    - name: k8s setting
      shell: "{{ item }}"
      with_items:
      - "sleep 15"
      - "echo 'fs.file-max = 65536' >> /etc/sysctl.conf "
      - "sysctl -p"
      - "echo `root hard nofile 65535 ' >> /etc/security/limits.conf"
      - "echo 'root soft nofile 65535 ' >> /etc/security/limits.conf"

- name: Replace IP address in files
  find:
    paths: iac-devops
    file_type: file
  register: found_files

- name: Replace IP address in each file
  replace:
    path: "{{ item.path }}"
    regexp: '10\.10\.30\.210'
    replace: "{{ repo }}"
  with_items: "{{ found_files.files }}"




    
