- hosts: controllplan01
  become: true
  become_user: root
  vars:
    ansible_become_pass: "@whdgus123!"
  tasks:
    - name: haproxy.yaml ip setup
      shell: "{{ item }}"
      with_items:
      - "wget http://192.168.110.201:8081/repository/filerepo/deployfile/iac.tar.gz"
      - "tar xvzf iac.tar.gz"
      - "kubectl get configmap kube-proxy -n kube-system -o yaml  |sed -e 's/mode: \"\"/mode: \"ipvs\"/'|kubectl apply -f - -n kube-system"
      - "kubectl get configmap kube-proxy -n kube-system -o yaml |sed -e 's/strictARP: false/strictARP: true/' |kubectl apply -f - -n kube-system"
      - "kubectl apply -f iac-devops/cicd/apps-helm-chart/apps/metallb-native.yaml"
      - "kubeca apply -f ip.yaml "
      - "kubectl apply -f pool.yaml"
      - "helm repo add rook-release http://192.168.110.201:8081/repository/rook-ceph"
      - "helm install --create-namespace --namespace rook-ceph rook-ceph rook-release/rook-ceph -f iac-devops/cicd/apps-helm-chart/apps/rook-ceph-values.yaml"
      - "sleep 120"
      - "helm install --create-namespace --namespace rook-ceph rook-ceph-cluster rook-release/rook-ceph-cluster -f iac-devops/cicd/apps-helm-chart/apps/rook-ceph-cluster-values.yaml"
      - "sleep "200"
      - "helm repo add argo http://192.168.110.201:8081/repository/argocd "
      - "helm install --create-namespace --namespace argocd argocd argo/argo-cd  -f iac-devops/cicd/apps-helm-chart/apps/values-argocd.yaml -n argocd"
      - "helm repo add goharbor http://192.168.110.201:8081/repository/harbor-helm"
      - "helm install --create-namespace --namespace harbor harbor goharbor/harbor -f iac-devops/cicd/apps-helm-chart/apps/harbor_values.yaml -n harbor"
      #- "helm repo add prometheus-community http://192.168.110.201:8081/repository/grfana-helm/"
      #- "helm install --create-namespace --namespace monitor prometheus prometheus-community/kube-prometheus-stack -f kube-prometheus-stack-values.yaml -n monitor"
      register: result

    - name: 결과 출력
      debug:
        var: result