---
- hosts: all
  become: true
  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Update all packages
      yum:
        name: '*'
        state: latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: Install essential packages
      apt:
        name: ['vim', 'curl', 'wget', 'unzip', 'tcpflow', 'cockpit', 'net-tools']
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install essential packages
      yum:
        name: ['vim', 'curl', 'wget', 'unzip', 'tcpflow', 'cockpit', 'net-tools', 'sysstat']
        state: present
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: Install chrony
      apt:
        name: chrony
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install chrony
      yum:
        name: chrony
        state: present
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    
    - name: Install btop (Debian/Ubuntu)
      block:
        - name: Install btop
          apt:
            name: ['build-essential', 'cmake', 'libncursesw5-dev', 'libsystemd-dev', 'pkg-config','btop']
            state: present
        

    - name: Install EPEL repository (CentOS/RedHat)
      yum:
        name: epel-release
        state: present
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: Install btop (CentOS/RedHat)
      yum:
        name: btop
        state: present
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

   
    - name: Add sudo group to sudoers file
      lineinfile:
        path: /etc/sudoers
        state: present
        line: '%sudo   ALL=(ALL:ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Ensure sudo group exists
      group:
        name: sudo
        state: present

   

    - name: Configure SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        line: PermitRootLogin no
        state: present

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted

    - name: Set open file limit (Debian/Ubuntu)
      block:
        - name: Set open file limit
          lineinfile:
            path: /etc/security/limits.conf
            line: '* hard nofile 65536'
            state: present

        - name: Set open file limit for root
          lineinfile:
            path: /etc/security/limits.conf
            line: 'root hard nofile 65536'
            state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Set open file limit (CentOS/RedHat)
      block:
        - name: Create a file for open file limits
          file:
            path: /etc/security/limits.d/99-openfile.conf
            state: touch
            mode: '0644'

        - name: Set open file limit
          lineinfile:
            path: /etc/security/limits.d/99-openfile.conf
            line: '* hard nofile 65536'
            state: present

        - name: Set open file limit for root
          lineinfile:
            path: /etc/security/limits.d/99-openfile.conf
            line: 'root hard nofile 65536'
            state: present
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    