- hosts: all
  become: yes
  tasks:
    - name: Run modprobe command
      command: modprobe vhost_net

    - name: Add vhost_net to /etc/modules
      lineinfile:
        path: /etc/modules
        line: 'vhost_net'
        state: present
    - name: install yq setting
      shell: "{{ item }}"
      with_items:
        - "virsh net-define /root/host-bridge.xml"
        - "virsh net-start host-bridge"
        - "virsh net-autostart host-bridge"
        
  