- hosts: all
  become: yes
  tasks:
    - name: Clone a repo with separate git directory
      ansible.builtin.git:
        repo: https://github.com/wjswhdgus123/ansible.git
        dest: /tmp/ansible
   
    - name: install yq setting
      shell: "{{ item }}"
      with_items:
        - "wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq"
        - "chmod +x /usr/bin/yq"
        - "yq -i 'del(.network.ethernets.{{ ansible_default_ipv4.interface }})' /etc/netplan/00-installer-config.yaml"
   
    - name: Copy netplan YAML file to /etc/netplan/
      copy:
        src: /tmp/ansible/kvm/01.bride.yaml
        dest: /etc/netplan/01.bride.yaml
        remote_src: yes
        
      

    - name: Update Interface
      ansible.builtin.replace:
        path: /etc/netplan/01.bride.yaml
        regexp: 'enp6s0'  # 변경할 패턴 정규식
        replace: "{{ ansible_default_ipv4.interface }}"  # 새로운 문자열

    - name: Update Interface
      ansible.builtin.replace:
        path: /etc/netplan/01.bride.yaml
        regexp: '192\.168\.110\.10'  # 변경할 패턴 정규식
        replace: "{{ ansible_default_ipv4.address }}"  # 새로운 문자열

    - name: Update Interface
      ansible.builtin.replace:
        path: /etc/netplan/01.bride.yaml
        regexp: '192\.168\.110\.1'  # 변경할 패턴 정규식
        replace: "{{ ansible_default_ipv4.gateway }}"  # 새로운 문자열
    
    - name: k8s setting
      shell: "{{ item }}"
      with_items:
        - "netplan generate"
        - "netplan --debug apply"

    - name: Create host-bridge.xml
      blockinfile:
        path: host-bridge.xml
        block: |
          <network>
            <name>host-bridge</name>
            <forward mode="bridge"/>
            <bridge name="br0"/>
          </network>
      

    
