- hosts: all
  become: yes
  tasks:
    - name: Create /kvm directory
      file:
        path: /kvm
        state: directory
        owner: www-data
        group: kvm
        mode: '0755'

    - name: Add www-data to kvm group
      user:
        name: www-data
        groups: kvm
        append: yes

    - name: Change www-data home directory to /kvm
      user:
        name: www-data
        home: /kvm

    - name: Clone a repo with separate git directory
      ansible.builtin.git:
        repo: https://github.com/retspen/webvirtcloud
        dest: /kvm/webvirtcloud/
    
    - name: webkvm setting
      shell: "{{ item }}"
      with_items:
      
        - "cp /kvm/webvirtcloud/webvirtcloud/settings.py.template /kvm/webvirtcloud/webvirtcloud/settings.py"
        - "cp /kvm/webvirtcloud/conf/supervisor/webvirtcloud.conf /etc/supervisor/conf.d"
        - "cp /kvm/webvirtcloud/conf/nginx/webvirtcloud.conf /etc/nginx/conf.d"
        
   
    - name: Update Interface
      ansible.builtin.replace:
        path: /kvm/webvirtcloud/webvirtcloud/settings.py
        regexp: "SECRET_KEY = \"\""  # 변경할 패턴 정규식
        replace: "SECRET_KEY = \"@whdgus123!\""

    - name: webkvm setting
      shell: "{{ item }}"
      with_items:
        - "chown -R www-data:kvm /kvm/webvirtcloud/"
        - "virtualenv -p python3 /kvm/webvirtcloud/venv"
        - "source /kvm/webvirtcloud/venv/bin/activate"
        - "pip install -r /kvm/webvirtcloud/conf/requirements.txt"
        - "python3 /kvm/webvirtcloud/manage.py migrate"
        - "chown -R www-data.kvm /kvm/"
        - "rm /etc/nginx/sites-enabled/default"
        - "python3 /kvm/webvirtcloud/manage.py migrate"
        