- name: Change hostname
  hosts: all
  become: true
  tasks:
    - name: Set new hostname
      hostname:
        name: "{{ hostname }}"
      register: "check_log"
  
    - debug:
        msg: "{{ check_log }}"