- name: Set maximum open file limit in limits.conf
  hosts: all
  become: true
  tasks:
    - name: Add or modify the limits for maximum open files
      lineinfile:
        path: /etc/security/limits.conf
        line: |
          * hard nofile 65536
          * soft nofile 65536
        state: present
        backrefs: yes