- hosts: all
  become: yes
  tasks:
   - name: Update and upgrade apt packages
     apt:
       upgrade: yes
       update_cache: yes
       cache_valid_time: 86400 #One day

   - name: install curl 
     apt:
       name: curl
       state: present
       update_cache: true

   - name: install iftop 
     apt:
       name: iftop
       state: present
       update_cache: true

  
   
   - name: install ntp 
     apt:
       name: chrony
       state: present
       update_cache: true
       
   - name: install nfs-common
     apt:
       name: nfs-common
       state: present
       update_cache: true

   - name: install nfs-common
     apt:
       name: libpam-pwquality
       state: present
       update_cache: true
   
   - name: install sysstat
     apt:
       name: sysstat
       state: present
       update_cache: true
   
   - name: install tcptraceroute
     apt:
       name: tcptraceroute
       state: present
       update_cache: true
    
   - name: install tcpflow
     apt:
       name: tcpflow
       state: present
       update_cache: true
    
   - name: install net-tools
     apt:
       name: net-tools
       state: present
       update_cache: true