apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storege-harbornfs
provisioner: kubernetes.io/nfs
parameters:
  server: ceph02.bestpath.co.kr
  path: "/NFS/harbor"



apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-registry
  namespace: harbor
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storege-harbornfs
  nfs:
    server: ceph02.bestpath.co.kr
    path: /NFS/harbor
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-jobservice
  namespace: harbor
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storege-harbornfs
  nfs:
    server: ceph02.bestpath.co.kr
    path: /NFS/harbor
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-database
  namespace: harbor
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storege-harbornfs
  nfs:
    server: ceph02.bestpath.co.kr
    path: /NFS/harbor
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-redis
  namespace: harbor
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storege-harbornfs
  nfs:
    server: ceph02.bestpath.co.kr
    path: /NFS/harbor/redis
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-trivy
  namespace: harbor
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storege-harbornfs
  nfs:
    server: ceph02.bestpath.co.kr
    path: /NFS/harbor/trivy