- hosts: all
  become: yes
  tasks:
    - name: Get unallocated physical disks using fdisk
      shell: "fdisk -l | grep \"Disk /dev/\" | grep -Ev \"mapper|identifier|Disklabel|loop\""
      register: disk_fdisk

    - name: Get unallocated physical disks using pvs
      shell: "pvs | awk '{print $1}' | grep dev"
      register: disk_pvs

    - debug:
        msg: "Unallocated disks (fdisk): {{ disk_fdisk.stdout_lines }}"
    
    - debug:
        msg: "Unallocated disks (pvs): {{ disk_pvs.stdout_lines }}"
