- hosts: all
  become: yes
  tasks:
    - name: Format disks with xfs and create mount points
      command: "umount {{ item.mount_point }}"
      loop: "{{ disk_info }}"
      register: mkfs_output
      when: disk_info is defined and disk_info | length > 0
      ignore_errors: yes

    - name: Create partitions using parted
      command: "parted -s {{ item.disk }} mklabel gpt mkpart primary 0% {{ item.size }}"
      loop: "{{ disk_partitions }}"
      when: disk_partitions is defined and disk_partitions | length > 0
    
    - name: Format disks with xfs and create mount points
      command: "mkfs.xfs -f -L {{ item.item.disk_label }} /dev/{{ item.item.disk_path }}"
      loop: "{{ mkfs_output.results }}"
      when: disk_info is defined and disk_info | length > 0


    - name: Create mount directories
      file:
        path: "{{ item.item.mount_point }}"
        state: directory
      loop: "{{ mkfs_output.results }}"
      when: mkfs_output is defined and mkfs_output.results | length > 0

    - name: Add entries to fstab
      lineinfile:
        path: "/etc/fstab"
        line: "LABEL={{ item.item.disk_label }} {{ item.item.mount_point }} xfs defaults 0 1"
        create: yes
      loop: "{{ mkfs_output.results }}"
      when: mkfs_output is defined and mkfs_output.results | length > 0
    
  
    - name: Create MinIO user group
      group:
        name: minio-user
        state: present
        system: yes

    - name: Create MinIO system user
      user:
        name: minio-user
        comment: "MinIO System User"
        system: yes
        group: minio-user
        shell: /bin/false  # 로그인 쉘 없는 시스템 계정으로 설정

    - name: Change ownership of directories
      file:
        path: "{{ item.item.mount_point }}"
        owner: minio-user
        group: minio-user
        recurse: yes
      loop: "{{ mkfs_output.results }}"
   