---
- hosts: all
  gather_facts: no

  tasks :
    - name: gogo
      shell: "sed -i 's/:1....:/:18107:/g' /etc/shadow"
      register: final_result
      ignore_errors: True

    - name: result gogosing
      debug: var=final_result.stdout_lines
#      when: final_result.rc == 0