---
- hosts: all
  gather_facts: no

  tasks :
    - name: gogo
      shell: "echo -e 'tnpqhfp^^10\ntnpqhfp^^10' | passwd root"
      register: final_result
      ignore_errors: True

    - name: result gogosing
      debug: var=final_result.stdout_lines
#      when: final_result.rc == 0