---
- hosts: all
  gather_facts: no

  tasks :
    - name: Print user info
      shell: "chage -E '2023-12-31' {{ user }}"
      register: user_info
      ignore_errors: True

    - name: result gogosing
      debug: var=user_info.stdout_lines
      when: user_info.rc == 0
